### ISSUE TITLE
uri parse fail

### ISSUE THREAD

**Issue by foxmuldercp** [mmriis/simpleidn#10]
fail case:

> SimpleIDN.to_ascii('http://домен.укр/')  
> => "xn--http://-5ggj3emj.xn--/-stbsk"
> estimated result for valid:
> SimpleIDN.to_ascii('http://домен.укр')
> => "http://xn--d1acufc.xn--j1amh/"

URI.parse fails on non ascii domains, so it will be good for regex, which drop all non-domain name content via regexp.

**Comment by mmriis** [comment]
Sanitize your input. SimpleIDN isn't doing anything wrong.
