### ISSUE TITLE
Non-ascii hostname converted to punycode using to_ascii method is not resolving

### ISSUE THREAD

**Issue by lalithachitharanjan** [mmriis/simpleidn#11]
The hostname cnwin2k8中国.avol.com is converted using to_ascii method as xn--cnwin2k8-sd0mx14e.avol.com but it fails in ruby's Socket class with the following error Net::LDAP::Error: getaddrinfo: 不知道这样的主机. The following is the code snippet I tried in the console

host = SimpleIDN.to_ascii("cnwin2k8中国.avol.com")

 ldap = Net::LDAP.new(:host => host,
 :port => "389",
 :encryption => :simple_tls,
 :base => "DC=avol,DC=com",
  :auth => {
  :username => "administrator",
 :method => :simple,
 :password => "password" }
  )

ldap.bind

The non-ascii character in the hostname is chinese and it is AD domain controller. Let me know if you need any more details

**Comment by mmriis** [comment]
I cannot reproduce the error. 

`test.rb:`
```ruby
require 'simpleidn'

puts SimpleIDN::to_unicode('xn--cnwin2k8-sd0mx14e.avol.com')
puts SimpleIDN::to_ascii("cnwin2k8中国.avol.com")`
```

```bash
$ ruby test.rb
cnwin2k8中国.avol.com
xn--cnwin2k8-sd0mx14e.avol.com
```

**Comment by mmriis** [comment]
Closing this.
