### ISSUE TITLE
Invalid encoding of https:// protocols

### ISSUE THREAD

**Issue by JaniszM** [mmriis/simpleidn#16]
I have found a little bug. If IDN contains `https://` protocol in its name then it is badly encoded.

Example:
```
observedServices = [
  'zgłaszam.pl',
  'https://zgłaszam.pl',
  'www.zgłaszam.pl',
  'https://www.zgłaszam.pl'
]
```

Output of `observedServices.each { |s| p SimpleIDN.to_ascii(s)}` is:
```
xn--zgaszam-ojb.pl
xn--https://zgaszam-8sc.pl     # THIS ONE IS INVALID
www.xn--zgaszam-ojb.pl
https://www.xn--zgaszam-ojb.pl
```

Expecting to have:
```
xn--zgaszam-ojb.pl
https://xn--zgaszam-ojb.pl    # VALID ONE
www.xn--zgaszam-ojb.pl
https://www.xn--zgaszam-ojb.pl
```

**Comment by bestwebua** [comment]
I think you should use it just for domain, not for protocol.

**Comment by mmriis** [comment]
This is not really a bug. Don't try to encode protocol.
