### ISSUE TITLE
gem install simpleidn problems

### ISSUE THREAD

**Issue by kepes** [mmriis/simpleidn#4]
Hi,

I try to install it but I got this errors:

unable to convert U+00F8 from UTF-8 to US-ASCII for lib/simpleidn.rb, skipping
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for LICENCE, skipping
unable to convert U+00F8 from UTF-8 to US-ASCII for Rakefile, skipping
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for README.rdoc, skipping
unable to convert U+00F8 from UTF-8 to US-ASCII for spec/idn.rb, skipping

I think the problem is in the comments where you put møllerriis.com

**Comment by mmriis** [comment]
Closing since no reply.
